=== LABSS/gloderss/src/main/resources/conf/batch.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

	<element name="batch">
		<complexType>
			<sequence>
				<element name="base" type="string" />
				<element name="output" type="string" />
				<element name="replica" type="nonNegativeInteger" />
				<element name="xmlScenario" type="string" />
				<element name="xsdScenario" type="string" />
				<element name="header" type="string" />
				<element name="general" type="string" />
				<element name="communication" type="string" />
				<element maxOccurs="1" name="citizens">
					<complexType>
						<sequence>
							<element minOccurs="1" maxOccurs="unbounded" name="content">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="code" type="string" />
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element maxOccurs="1" name="states">
					<complexType>
						<sequence>
							<element minOccurs="1" maxOccurs="unbounded" name="content">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="code" type="string" />
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element maxOccurs="1" name="mafias">
					<complexType>
						<sequence>
							<element minOccurs="1" maxOccurs="unbounded" name="content">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="code" type="string" />
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element maxOccurs="1" name="ios">
					<complexType>
						<sequence>
							<element minOccurs="1" maxOccurs="unbounded" name="content">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="code" type="string" />
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="tail" type="string" />
			</sequence>
		</complexType>
	</element>
</schema>

=== LABSS/gloderss/src/test/resources/conf/sampleBatch.xml
<?xml version="1.0" encoding="UTF-8"?>
<batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="batch.xsd">

	<base>./src/test/resources/conf</base>
	<output>./output</output>
	<replica>10</replica>

	<xmlScenario>./src/test/resources/conf/scenario.xml</xmlScenario>
	<xsdScenario>./src/main/resources/conf/scenario.xsd</xsdScenario>

	<header>header.txt</header>
	<general>general.txt</general>
	<communication>communication.txt</communication>
	<citizens>
		<content code="iw03-nw07">citizens-iw03-nw07.txt</content>
		<content code="iw05-nw05">citizens-iw05-nw05.txt</content>
	</citizens>
	<states>
		<content code="weak-noNorm">state-weak-noNorm.txt</content>
		<content code="weak-norm">state-weak-norm.txt</content>
		<content code="strong-noNorm">state-strong-noNorm.txt</content>
		<content code="strong-norm">state-strong-norm.txt</content>
	</states>
	<mafias>
		<content code="violent-low">mafia-violent-low.txt</content>
		<content code="violent-medium">mafia-violent-medium.txt</content>
		<content code="violent-high">mafia-violent-high.txt</content>
		<content code="hidden-low">mafia-hidden-low.txt</content>
		<content code="hidden-medium">mafia-hidden-medium.txt</content>
		<content code="hidden-high">mafia-hidden-high.txt</content>
	</mafias>
	<ios>
		<content code="inactive">io-inactive.txt</content>
		<content code="active">io-active.txt</content>
	</ios>
	<tail>tail.txt</tail>
</batch>
