=== LABSS/gloderss/src/main/resources/conf/randomBatch.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

	<element name="randomBatch">
		<complexType>
			<sequence>
				<element name="outputDir" type="string" />
				<element name="outputFile" type="string" />
				<element name="replica" type="positiveInteger" />
				<element name="xmlScenario" type="string" />
				<element name="xsdScenario" type="string" />
				<element maxOccurs="1" name="changes">
					<complexType>
						<sequence>
							<element minOccurs="1" maxOccurs="unbounded" name="change">
								<complexType>
									<sequence>
										<element name="name" type="string" />
										<element name="parameter" type="string" />
										<element name="type" type="string" />
										<element name="value" type="string" />
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== LABSS/gloderss/src/main/resources/conf/sensitivity-analysis/randomBatch.xml
<?xml version="1.0" encoding="UTF-8"?>
<randomBatch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="randomBatch.xsd">

	<outputDir>/data/downloads/garbage/SS17/0.49-0.51/data/sensitivity-analysis</outputDir>
	<outputFile>config.csv</outputFile>
	<replica>400</replica>

	<xmlScenario>src/main/resources/conf/sensitivity-analysis/scenario.xml</xmlScenario>
	<xsdScenario>src/main/resources/conf/scenario.xsd</xsdScenario>

	<changes>
<!-- 		<change>
			<name>numberPoliceOfficers</name>
			<parameter>/scenario/state/numberPoliceOfficers</parameter>
			<type>FIXED</type>
			<value>5,10,15,20</value>
		</change>  -->
		<change>
			<name>generalInvestigationDurationPDF</name>
			<parameter>/scenario/state/generalInvestigationDurationPDF</parameter>
			<type>NORMAL-RANDOM</type>
			<value>10,100!5,10</value>
		</change>
		<change>
			<name>bureaucraticActivityDurationPDF</name>
			<parameter>/scenario/state/bureaucraticActivityDurationPDF</parameter>
			<type>NORMAL-RANDOM</type>
			<value>50,100!5,10</value>
		</change>
		<change>
			<name>specificInvestigationDurationPDF</name>
			<parameter>/scenario/state/specificInvestigationDurationPDF</parameter>
			<type>NORMAL-RANDOM</type>
			<value>10,300!5,10</value>
		</change>
		<change>
			<name>specificInvestigationProbability</name>
			<parameter>/scenario/state/specificInvestigationProbability</parameter>
			<type>UNIFORM</type>
			<value>0.5,1.0</value>
		</change>
		<change>
			<name>captureProbability</name>
			<parameter>/scenario/state/captureProbability</parameter>
			<type>UNIFORM</type>
			<value>0.2,0.8</value>
		</change>
	 	<change>
			<name>custodyDurationPDF</name>
			<parameter>/scenario/state/custodyDurationPDF</parameter>
			<type>CONSTANT-RANDOM</type>
			<value>10,150</value>
		</change>
		<change>
			<name>convictionProbability</name>
			<parameter>/scenario/state/convictionProbability</parameter>
			<type>UNIFORM</type>
			<value>0.2,0.8</value>
		</change>
	 	<change>
			<name>imprisonmentDurationPDF</name>
			<parameter>/scenario/state/imprisonmentDurationPDF</parameter>
			<type>NORMAL-RANDOM</type>
			<value>100,500!5,100</value>
		</change>
<!-- 		<change>
			<name>numberMafiosi</name>
			<parameter>/scenario/mafia/numberMafiosi</parameter>
			<type>FIXED</type>
			<value>5,10,15,20</value>
		</change> -->
		<change>
			<name>extortionLevel</name>
			<parameter>/scenario/mafia/extortionLevel</parameter>
			<type>UNIFORM</type>
			<value>0.01,0.10</value>
		</change>
		<change>
			<name>punishmentSeverity</name>
			<parameter>/scenario/mafia/punishmentSeverity</parameter>
			<type>UNIFORM</type>
			<value>0.5,1.0</value>
		</change>
		<change>
			<name>punishmentProbability</name>
			<parameter>/scenario/mafia/punishmentProbability</parameter>
			<type>UNIFORM</type>
			<value>0.5,1.0</value>
		</change>
		<change>
			<name>maximumBenefit</name>
			<parameter>/scenario/mafia/maximumBenefit</parameter>
			<type>UNIFORM</type>
			<value>0.05,0.1</value>
		</change>
	</changes>
</randomBatch>
