=== LABSS/gloderss/src/main/resources/conf/scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

	<element name="scenario">
		<complexType>
			<sequence>
				<!-- General Configuration Information -->
				<element maxOccurs="1" name="general">
					<complexType>
						<sequence>
							<element name="numberReplications" type="nonNegativeInteger" />
							<element name="numberCycles" type="double" />
							<element maxOccurs="1" name="seeds">
								<complexType>
									<choice maxOccurs="unbounded" minOccurs="0">
										<element name="seed" type="nonNegativeInteger" />
									</choice>
								</complexType>
							</element>
							<element maxOccurs="1" name="output">
								<complexType>
									<sequence>
										<element name="directory" type="string" />
										<element name="filename" type="string" />
										<element name="append" type="boolean" />
										<element name="separator" type="string" />
										<element name="writeFrequency" type="nonNegativeInteger" />
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

				<!-- Consumers Configuration Information -->
				<element maxOccurs="1" name="consumers">
					<complexType>
						<sequence>
							<element maxOccurs="unbounded" name="consumer">
								<complexType>
									<sequence>
										<element name="numberConsumers" type="nonNegativeInteger" />

										<!-- Reputation -->
										<element name="reputation">
											<complexType>
												<sequence>
													<element name="entrepreneurPayer">
														<simpleType>
															<restriction base="double">
																<minInclusive value="0.0" />
																<maxInclusive value="1.0" />
															</restriction>
														</simpleType>
													</element>
												</sequence>
											</complexType>
										</element>

										<!-- Normative -->
										<element name="normativeXML" type="string" />
										<element name="normativeXSD" type="string" />
										<element name="individualWeight">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
													<maxInclusive value="1.0" />
												</restriction>
											</simpleType>
										</element>
										<element name="normativeWeight">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
													<maxInclusive value="1.0" />
												</restriction>
											</simpleType>
										</element>
										<element maxOccurs="1" name="normsSalience">
											<complexType>
												<sequence>
													<element maxOccurs="unbounded" name="normSalience">
														<complexType>
															<attribute name="id" type="nonNegativeInteger" />
															<attribute name="salience">
																<simpleType>
																	<restriction base="double">
																		<minInclusive value="0.0" />
																		<maxInclusive value="1.0" />
																	</restriction>
																</simpleType>
															</attribute>
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

				<!-- Entrepreneurs Configuration Information -->
				<element maxOccurs="1" name="entrepreneurs">
					<complexType>
						<sequence>
							<element maxOccurs="unbounded" name="entrepreneur">
								<complexType>
									<sequence>
										<element name="numberEntrepreneurs" type="nonNegativeInteger" />

										<!-- Economic -->
										<element name="wealth">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
												</restriction>
											</simpleType>
										</element>
										<element name="periodicityWage" type="nonNegativeInteger" />
										<element name="minimumWage">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
												</restriction>
											</simpleType>
										</element>
										<element name="maximumWage">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
												</restriction>
											</simpleType>
										</element>
										<element name="variationWage">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
													<maxInclusive value="1.0" />
												</restriction>
											</simpleType>
										</element>

										<!-- State -->
										<element name="collaborationProbability">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
													<maxInclusive value="1.0" />
												</restriction>
											</simpleType>
										</element>

										<!-- Intermediary Organization -->
										<element name="affiliated" type="boolean" />

										<!-- Reputation -->
										<element name="reputation">
											<complexType>
												<sequence>
													<element name="stateProtector">
														<simpleType>
															<restriction base="double">
																<minInclusive value="0.0" />
																<maxInclusive value="1.0" />
															</restriction>
														</simpleType>
													</element>
													<element name="statePunisher">
														<simpleType>
															<restriction base="double">
																<minInclusive value="0.0" />
																<maxInclusive value="1.0" />
															</restriction>
														</simpleType>
													</element>
													<element name="mafiaPunisher">
														<simpleType>
															<restriction base="double">
																<minInclusive value="0.0" />
																<maxInclusive value="1.0" />
															</restriction>
														</simpleType>
													</element>
												</sequence>
											</complexType>
										</element>

										<!-- Normative -->
										<element name="normativeXML" type="string" />
										<element name="normativeXSD" type="string" />
										<element name="individualWeight">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
													<maxInclusive value="1.0" />
												</restriction>
											</simpleType>
										</element>
										<element name="normativeWeight">
											<simpleType>
												<restriction base="double">
													<minInclusive value="0.0" />
													<maxInclusive value="1.0" />
												</restriction>
											</simpleType>
										</element>
										<element maxOccurs="1" name="normsSalience">
											<complexType>
												<sequence>
													<element maxOccurs="unbounded" name="normSalience">
														<complexType>
															<attribute name="id" type="nonNegativeInteger" />
															<attribute name="salience">
																<simpleType>
																	<restriction base="double">
																		<minInclusive value="0.0" />
																		<maxInclusive value="1.0" />
																	</restriction>
																</simpleType>
															</attribute>
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>

									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

				<!-- State Configuration Information -->
				<element maxOccurs="1" name="state">
					<complexType>
						<sequence>
							<!-- Police -->
							<element name="numberPoliceOfficers" type="nonNegativeInteger" />
							<element name="investigativeDuration" type="nonNegativeInteger" />
							<element name="captureProbability">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
										<maxInclusive value="1.0" />
									</restriction>
								</simpleType>
							</element>

							<!-- Justice -->
							<element name="incarcerationProbability">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
										<maxInclusive value="1.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="incarcerationDuration" type="nonNegativeInteger" />
							<element name="proportionTransferFondo">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
										<maxInclusive value="1.0" />
									</restriction>
								</simpleType>
							</element>
						</sequence>
					</complexType>
				</element>

				<!-- Mafia Configuration Information -->
				<element maxOccurs="1" name="mafia">
					<complexType>
						<sequence>
							<element name="numberMafiosi" type="nonNegativeInteger" />
							<element name="wealth">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="demandMean">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="demandStDev">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="extortionLevel">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="punishmentSeverity">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="punishmentProbability">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
										<maxExclusive value="1.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="minimumBenefit">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="maximumBenefit">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
									</restriction>
								</simpleType>
							</element>
							<element name="pentitiProbability">
								<simpleType>
									<restriction base="double">
										<minInclusive value="0.0" />
										<maxInclusive value="1.0" />
									</restriction>
								</simpleType>
							</element>
						</sequence>
					</complexType>
				</element>

				<!-- Intermediary Organization Configuration Information -->
				<element maxOccurs="1" name="intermediaryOrg" />

			</sequence>
		</complexType>
	</element>
</schema>

=== LABSS/gloderss/src/main/resources/conf/scenario.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="scenario.xsd">

	<!-- General Configuration Information -->
	<general>
		<numberReplications>2</numberReplications>
		<numberCycles>10000</numberCycles>
		<seeds>
			<seed>1</seed>
			<seed>2</seed>
		</seeds>
		<output>
			<directory>./output</directory>
			<filename>database.csv</filename>
			<append>false</append>
			<separator>;</separator>
			<writeFrequency>1000</writeFrequency>
		</output>
	</general>

	<!-- Consumers Configuration Information -->
	<consumers>
		<consumer>
			<numberConsumers>10</numberConsumers>

			<!-- Reputation -->
			<reputation>
				<entrepreneurPayer>0.5</entrepreneurPayer>
			</reputation>

			<!-- Normative -->
			<normativeXML>src/main/resources/conf/consumer.xml</normativeXML>
			<normativeXSD>src/main/resources/conf/emilia.xsd</normativeXSD>
			<individualWeight>0.5</individualWeight>
			<normativeWeight>0.5</normativeWeight>
			<normsSalience>
				<normSalience id="4" salience="0.3" />
				<normSalience id="5" salience="0.9" />
			</normsSalience>
		</consumer>
	</consumers>

	<!-- Entrepreneurs Configuration Information -->
	<entrepreneurs>
		<entrepreneur>
			<numberEntrepreneurs>10</numberEntrepreneurs>

			<!-- Economic -->
			<wealth>1000.00</wealth>
			<periodicityWage>30</periodicityWage>
			<minimumWage>500.00</minimumWage>
			<maximumWage>1000.00</maximumWage>
			<variationWage>0.5</variationWage>

			<!-- State -->
			<collaborationProbability>0.9</collaborationProbability>

			<!-- Intermediary Organization -->
			<affiliated>false</affiliated>

			<!-- Reputation -->
			<reputation>
				<stateProtector>0.5</stateProtector>
				<statePunisher>0.9</statePunisher>
				<mafiaPunisher>0.9</mafiaPunisher>
			</reputation>

			<!-- Normative -->
			<normativeXML>src/main/resources/conf/entrepreneur.xml</normativeXML>
			<normativeXSD>src/main/resources/conf/emilia.xsd</normativeXSD>
			<individualWeight>0.5</individualWeight>
			<normativeWeight>0.5</normativeWeight>
			<normsSalience>
				<normSalience id="0" salience="0.3" />
				<normSalience id="1" salience="0.9" />
				<normSalience id="2" salience="0.9" />
				<normSalience id="3" salience="0.9" />
			</normsSalience>
		</entrepreneur>
	</entrepreneurs>

	<!-- State Configuration Information -->
	<state>
		<!-- Police -->
		<numberPoliceOfficers>10</numberPoliceOfficers>
		<investigativeDuration>3</investigativeDuration>
		<captureProbability>0.7</captureProbability>

		<!-- Justice -->
		<incarcerationProbability>0.8</incarcerationProbability>
		<incarcerationDuration>15</incarcerationDuration>
		<proportionTransferFondo>0.5</proportionTransferFondo>
	</state>

	<!-- Mafia Configuration Information -->
	<mafia>
		<numberMafiosi>5</numberMafiosi>
		<wealth>0.00</wealth>
		<demandMean>30</demandMean>
		<demandStDev>2</demandStDev>
		<extortionLevel>0.1</extortionLevel>
		<punishmentSeverity>0.6</punishmentSeverity>
		<punishmentProbability>0.5</punishmentProbability>
		<minimumBenefit>0.0</minimumBenefit>
		<maximumBenefit>1.5</maximumBenefit>
		<pentitiProbability>0.0</pentitiProbability>
	</mafia>

	<!-- Intermediary Organization Configuration Information -->
	<intermediaryOrg>
	</intermediaryOrg>

</scenario>
